# Generated by Django 4.2.7 on 2024-04-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('uname', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taskdate', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=20)),
                ('complete', models.CharField(max_length=10)),
                ('assign', models.CharField(max_length=30)),
            ],
        ),
    ]
