# Generated by Django 4.2.7 on 2024-04-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assign',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='desc',
            new_name='Division',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='Priority',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskdate',
            new_name='Type',
        ),
    ]
