# Generated by Django 4.2.7 on 2024-04-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_rename_priority_task_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Type',
            new_name='Status',
        ),
    ]
